server:
  port: 8080

base-url:
  context: /transformer-thermal-inspection

log:
  identifierKey: UUID
  isDebug: true

info:
  app:
    name: base-template
    msName: base-template

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: spdsmc123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rest:
  connect-timeout: 5000
  read-timeout: 20000
