server:
  port: 8080

base-url:
  context: /transformer-thermal-inspection

log:
  identifierKey: UUID
  isDebug: true

info:
  app:
    name: base-templatea
    msName: base-template

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dI82@#lA
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rest:
  connect-timeout: 5000
  read-timeout: 20000

python:
  exec: "C:\\Users\\Sahan\\AppData\\Local\\Programs\\Python\\Python310\\python.exe"
